modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="phalanx_smp"
version="1.2.0"
displayName="Phalanx SMP"
displayURL="https://github.com/iraxon"
logoFile="logo.png"
credits="Made with MCreator."
authors="COMMANDO66"
description="Random changes for Phalanx SMP"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.phalanx_smp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration